services:

  # PostgreSQL Database

  postgres:

    image: postgres:16

    container_name: postgres_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s


  # Redis Broker for Celery

  redis:

    image: redis:7

    container_name: redis_server

    restart: unless-stopped

    ports:
      - "6379:6379"


  # FastAPI Application

  app:

    build: .

    container_name: library_app

    restart: unless-stopped

    depends_on:

      postgres:
        condition: service_healthy

      redis:
        condition: service_started

    env_file:
      - .env

    volumes:
      # Share logs folder with host machine
      - ./logs:/app/logs

    ports:
      - "8000:8000"

    command:
      uvicorn main:app --host 0.0.0.0 --port 8000


  # Celery Worker
  
  celery_worker:

    build: .

    container_name: celery_worker

    restart: unless-stopped

    depends_on:

      redis:
        condition: service_started

      postgres:
        condition: service_healthy


    env_file:
      - .env


    environment:

      REDIS_HOST: redis

      REDIS_PORT: 6379


    volumes:

      # IMPORTANT:
      # Celery writes here
      # Host VS Code logs folder receives it
      - ./logs:/app/logs


    command:

      celery -A tasks.celery worker --loglevel=info


# Persistent Database Volume

volumes:

  postgres_data: