"""add authentication fields to members

Revision ID: 51ea3c5ff5e7
Revises: 3b741e61bb6d
Create Date: 2026-07-08 08:00:42.009534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ea3c5ff5e7'
down_revision: Union[str, Sequence[str], None] = '3b741e61bb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('username', sa.String(), nullable=False))
    op.add_column('members', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column(
    'members',
    sa.Column('role', sa.String(), nullable=False, server_default='member')
)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'members', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='unique')
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('members', 'role')
    op.drop_column('members', 'hashed_password')
    op.drop_column('members', 'username')
    # ### end Alembic commands ###
