name: Continuous Deployment

on:
  workflow_run:
    workflows:
      - Continuous Integration
    branches:
      - main
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "Cleaning old Docker resources"

            docker image prune -f
            docker container prune -f

            echo "Starting PostgreSQL"

            docker start postgres_db || true

            echo "Pull latest image"

            docker pull ghcr.io/maryamsaleemm/library-management-system:latest

            echo "Stopping old FastAPI"

            docker stop library_app || true
            docker rm library_app || true

            echo "Removing old Celery container (if it exists)"

            docker stop celery_worker || true
            docker rm celery_worker || true

            echo "Running Alembic Migrations"

            docker run --rm \
              --network host \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              --entrypoint alembic \
              ghcr.io/maryamsaleemm/library-management-system:latest \
              upgrade head

            echo "Starting FastAPI"

            docker run -d \
              --restart unless-stopped \
              --name library_app \
              --network host \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ghcr.io/maryamsaleemm/library-management-system:latest

            echo "Running Containers"

            docker ps

            echo "Application Logs"

            docker logs library_app --tail 20