name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - integration
      - staging
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  lint-test-build:

    runs-on: ubuntu-latest

    services:

      postgres:

        image: postgres:16

        env:
          POSTGRES_DB: library
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify PostgreSQL Connection
        run: |
          python - <<EOF
          import os
          import psycopg2

          conn = psycopg2.connect(
              host=os.environ["DB_HOST"],
              database=os.environ["DB_NAME"],
              user=os.environ["DB_USER"],
              password=os.environ["DB_PASSWORD"],
              port=os.environ["DB_PORT"]
          )

          print("PostgreSQL Connected Successfully")
          conn.close()
          EOF

      - name: Run Alembic Migration
        run: |
          alembic upgrade head

      - name: Run Flake8
        run: |
          flake8 . --exclude=migrations

      - name: Run Pytest
        run: |
          pytest -v

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        if: github.event_name == 'push'
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER/library-management-system:latest .

      - name: Push Docker Image
        if: github.event_name == 'push'
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$OWNER/library-management-system:latest

  deploy:

    needs: lint-test-build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "Starting PostgreSQL..."

            docker start postgres_db || true

            echo "Pulling latest image..."

            docker pull ghcr.io/maryamsaleemm/library-management-system:latest

            echo "Stopping old application..."

            docker stop library_app || true
            docker rm library_app || true

            echo "Running Alembic migrations..."

            docker run --rm \
              --network host \
              -e DB_HOST=localhost \
              -e DB_PORT=5432 \
              -e DB_NAME=library \
              -e DB_USER=postgres \
              -e DB_PASSWORD=postgres \
              --entrypoint alembic \
              ghcr.io/maryamsaleemm/library-management-system:latest \
              upgrade head

            echo "Starting new application..."

            docker run -d \
              --name library_app \
              --network host \
              -e DB_HOST=localhost \
              -e DB_PORT=5432 \
              -e DB_NAME=library \
              -e DB_USER=postgres \
              -e DB_PASSWORD=postgres \
              ghcr.io/maryamsaleemm/library-management-system:latest

            docker ps


          #  the PostgreSQL service initialization variables
          #  because GitHub Actions doesn't allow secrets in the services.env section. Since that PostgreSQL 
          #  instance is a temporary CI container created only
          #  for testing, those values are not production secrets."